# Generated by Django 2.1.5 on 2019-01-31 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField(max_length=200)),
                ('phone', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='VisitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(max_length=400)),
                ('bp', models.CharField(max_length=7)),
                ('disease_info', models.CharField(max_length=1000)),
                ('medicine', models.CharField(max_length=600)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Patient')),
            ],
        ),
    ]
